name: Sync Upstream

on:
  schedule:
    # Run once a day at midnight UTC
    - cron: '0 0 * * *'

  workflow_dispatch: # Allow manual trigger
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    # Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@main

    # Set up Git for syncing
    - name: Set up Git
      run: |
        git config user.name "qqsir-dev"
        git config user.email "qqsir@hotmail.com"

    # Add upstream repository
    - name: Add Upstream Remote
      run: |
        git remote add upstream https://github.com/VIKINGYFY/OpenWRT-CI.git
        git fetch upstream

    # Sync with upstream main branch
    - name: Merge Upstream Changes
      run: |
        git checkout main
        git merge upstream/main --allow-unrelated-histories -X theirs
        git push origin main
